### ISSUE TITLE
singularity hub can return HTML instead of expected json

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-container#102]
I saw a cryptic errors from datalad:
```
Expecting value: line 2 column 1 (char 1) [decoder.py:raw_decode:400] (JSONDecodeError)
```
upon containers-add.  The reason is that singularity hub might return html (not json) whenever it gets "pissed" due to high volume of requests from an IP:
```shell
(git)smaug:~/proj/repronim/containers[master]git
$> datalad --dbg containers-add bids-validator -i images/bids/bids-validator--1.3.1.sing --update --call-fmt '{img_dspath}/scripts/singularity_cmd run {img} {cmd}' -u shub://ReproNim/containers:bids-validator--1.3.1
Traceback (most recent call last):
  File "/usr/bin/datalad", line 8, in <module>
    main()
  File "/usr/lib/python3/dist-packages/datalad/cmdline/main.py", line 494, in main
    ret = cmdlineargs.func(cmdlineargs)
  File "/usr/lib/python3/dist-packages/datalad/interface/base.py", line 628, in call_from_parser
    ret = list(ret)
  File "/usr/lib/python3/dist-packages/datalad/interface/utils.py", line 435, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/usr/lib/python3/dist-packages/datalad/interface/utils.py", line 529, in _process_results
    for res in results:
  File "/usr/lib/python3/dist-packages/datalad_container/containers_add.py", line 222, in __call__
    imgurl = _resolve_img_url(url)
  File "/usr/lib/python3/dist-packages/datalad_container/containers_add.py", line 41, in _resolve_img_url
    shub_info = loads(req.text)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

> /usr/lib/python3/dist-packages/simplejson/decoder.py(400)raw_decode()
-> return self.scan_once(s, idx=_w(s, idx).end())
(Pdb) up
> /usr/lib/python3/dist-packages/simplejson/decoder.py(370)decode()
-> obj, end = self.raw_decode(s)
(Pdb) p s
'\n<!DOCTYPE html>\n<html>\n  <head>\n    <meta charset="UTF-8">\n    <title>Beep Boop, Not Found!</title>\n    <style>\n    #robot {\n        position: absolute;\n        top:25%;\n        left:25%;\n        text-align: center;\n        font-family: Roboto, sans-serif;\n    }\n    </style>\n    <meta http-equiv="X-UA-Compatible" content="IE=edge">\n    <meta charset="utf-8" />\n    <link href=\'https://fonts.googleapis.com/css?family=Roboto\' rel=\'stylesheet\' type=\'text/css\'>\n  </head>\n  <body>\n    <div id="robot">\n        <h1 style="color:#999">You\'ve done that too many times, try again tomorrow.</h1>\n        <img width="300px" src="/static/img/hang10_robot.png">\n    </div>\n  </body>\n</html>\n'
```

I guess we should at least fail with some descriptive message when we detect such kind of a response or (ideally for a user) implement "wait for it to calm down" behavior.  I bet there is some preset delay we could wait (I think ATM it is just some seconds or a few minutes).

**Comment by yarikoptic** [comment]
well, singularity hub is no more (we are maintaining archive/compatibility layer and it is so basic that nothing to fix really, see yourself at https://datasets.datalad.org/shub/_service_/serve.py ), the issue seems to not reproduce any longer

```shell
$> datalad --dbg containers-add bids-validator -i images/bids/bids-validator--1.3.1.sing --update --call-fmt '{img_dspath}/scripts/singularity_cmd run {img} {cmd}' -u shub://ReproNim/containers:bids-validator--1.3.1
[INFO   ] Initializing special remote datalad 
add(ok): .datalad/config (file)                                                                     
save(ok): . (dataset)                                                                               
action summary:                                                                                     
  add (ok: 1)
  save (ok: 1)
add(ok): .datalad/config (file)
save(ok): . (dataset)
containers_add(ok): /tmp/test/images/bids/bids-validator--1.3.1.sing (file)
action summary:
  add (ok: 1)
  containers_add (ok: 1)
  save (ok: 1)
```
