### ISSUE TITLE
Docker adapter tests fail on github aciton build

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad-container#112]
https://github.com/datalad/datalad/pull/3860/checks?check_run_id=294971073#step:10:32

<details>
<summary>errors</summary>

```
======================================================================
ERROR: datalad_container.adapters.tests.test_docker.TestAdapterBusyBox.test_containers_run
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 429, in newfunc
    return t(*(arg + (d,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/datalad_container/adapters/tests/test_docker.py", line 96, in test_containers_run
    ds.containers_run(["cat", "foo"], container_name="bb")
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/datalad/distribution/dataset.py", line 523, in apply_func
    return f(**kwargs)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 485, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 473, in return_func
    results = list(results)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 421, in generator_func
    result_log_level, **_kwargs):
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 516, in _process_results
    for res in results:
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/datalad_container/containers_run.py", line 138, in __call__
    sidecar=sidecar):
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/datalad/core/local/run.py", line 698, in run_command
    raise exc
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/datalad/core/local/run.py", line 468, in _execute_command
    expect_fail=True,
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/datalad/cmd.py", line 544, in run
    raise CommandError(str(cmd), msg, status, out[0], out[1])
datalad.support.exceptions.CommandError: CommandError: command 'python -m datalad_container.adapters.docker run .datalad/environments/bb/image cat foo' failed with exitcode 1
Failed to run 'python -m datalad_container.adapters.docker run .datalad/environments/bb/image cat foo' under '/tmp/datalad_temp_tree_test_containers_runs_ly60eu'. Exit code=1.
-------------------- >> begin captured logging << --------------------
datalad.utils: Level 5: Importing datalad.utils
datalad.utils: DEBUG: Maximal length of cmdline string (adjusted for safety margin): 1048576
datalad.utils: Level 5: Done importing datalad.utils
datalad.cmd: Level 9: Will use git under '/usr/lib/git-annex.linux' (no adjustments to PATH if empty string)
datalad.cmd: Level 9: Running: ['git', 'version']
datalad.cmd: Level 8: Finished running ['git', 'version'] with status 0
datalad.cmd: Level 9: Running: ['git', 'config', '-z', '-l', '--show-origin']
datalad.cmd: Level 8: Finished running ['git', 'config', '-z', '-l', '--show-origin'] with status 0
datalad.ui: Level 5: Starting importing ui
datalad.ui.dialog: Level 5: Starting importing ui.dialog
datalad.ui.dialog: Level 5: Done importing ui.dialog
datalad.ui: Level 5: Initiating UI switcher
datalad.ui: DEBUG: UI set to SilentConsoleLog(out=<TextIOWrapper>)
datalad.ui: Level 5: Done importing ui
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: datalad_container.adapters.tests.test_docker.TestAdapterBusyBox.test_save_and_run
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 602, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/datalad_container/adapters/tests/test_docker.py", line 79, in test_save_and_run
    out, _ = call(["run", image_dir, "ls"], cwd=path)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/datalad_container/adapters/tests/test_docker.py", line 28, in call
    **kwds)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/datalad/cmd.py", line 544, in run
    raise CommandError(str(cmd), msg, status, out[0], out[1])
datalad.support.exceptions.CommandError: CommandError: command '['/opt/hostedtoolcache/Python/3.7.5/x64/bin/python', '-m', 'datalad_container.adapters.docker', 'run', '/tmp/datalad_temp_test_save_and_runzqc9bc3n/image', 'ls']' failed with exitcode 1
Failed to run ['/opt/hostedtoolcache/Python/3.7.5/x64/bin/python', '-m', 'datalad_container.adapters.docker', 'run', '/tmp/datalad_temp_test_save_and_runzqc9bc3n/image', 'ls'] under '/tmp/datalad_temp_test_save_and_runzqc9bc3n'. Exit code=1. out= err=the input device is not a TTY

```

</details>

**Comment by kyleam** [comment]
Hmm, can't trigger it locally, so it might be travis-specific.

**Comment by kyleam** [comment]
Oy, I'm having issues today.  This is failing through a github workflow, so it doesn't make any sense to suppose this is a travis issue.  (Not to mention we already have the docker adapter tests passing on this extension's travis build, so it seems unlikely that some interaction between travis and datalad master is making this fail.)

So most likely this issue has nothing to do with the datalad master branch (as the title suggests); we're just seeing it there for the first time because that's the only place we have github workflows set up.  The github workflow isn't happy about the `-it` in the `docker run` call.  And I suppose it's got a point.
