### ISSUE TITLE
Recent test_schemes.test_docker error in datalad core test runs

### ISSUE THREAD

**Issue by kyleam** [datalad/datalad-container#126]
An error in test_schemes.test_docker popped up in datalad PRs in the last day or two.  Here's one example:

```
datalad_container.tests.test_schemes.test_docker ... ERROR
bb -> .datalad/environments/bb/image

Versions: annexremote=1.4.3 appdirs=1.4.4 boto=2.49.0 cmd:7z=16.02 cmd:annex=7.20190819+git2-g908476a9b-1~ndall+1 cmd:bundled-git=2.20.1 cmd:git=2.20.1 cmd:system-git=2.28.0 cmd:system-ssh=7.6p1 exifread=2.3.1 humanize=2.6.0 iso8601=0.1.12 keyring=21.4.0 keyrings.alt=3.4.0 msgpack=1.0.0 mutagen=1.45.1 requests=2.24.0 tqdm=4.48.2 wrapt=1.12.1
======================================================================
Obscure filename: str=b' "\';a&b&c\xce\x94\xd0\x99\xd7\xa7\xd9\x85\xe0\xb9\x97\xe3\x81\x82 `| ' repr=' "\';a&b&cΔЙקم๗あ `| '
ERROR: datalad_container.tests.test_schemes.test_docker
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='UTF-8'
----------------------------------------------------------------------
Environment: LANG='C.UTF-8' PATH='/opt/hostedtoolcache/Python/3.7.9/x64/bin:/opt/hostedtoolcache/Python/3.7.9/x64:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin' GIT_CONFIG_PARAMETERS="'init.defaultBranch=master'"
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 177, in _wrap_skip_if_no_network
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/tests/utils.py", line 731, in _wrap_with_tempfile
    return t(*(arg + (filename,)), **kw)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad_container/tests/test_schemes.py", line 31, in test_docker
    ds.containers_run(["ls", "/singularity"])
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/distribution/dataset.py", line 503, in apply_func
    return f(**kwargs)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 481, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 469, in return_func
    results = list(results)
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 400, in generator_func
    allkwargs):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/interface/utils.py", line 539, in _process_results
    for res in results:
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad_container/containers_run.py", line 140, in __call__
    sidecar=sidecar):
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/core/local/run.py", line 696, in run_command
    raise exc
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/core/local/run.py", line 473, in _execute_command
    expect_fail=True,
  File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/datalad/cmd.py", line 970, in run
    raise exc
datalad.support.exceptions.CommandError: CommandError: ''singularity exec .datalad/environments/bb/image ls /singularity'' failed with exitcode 255 under /tmp/datalad_temp_test_dockern6l173f7
```

https://github.com/datalad/datalad/pull/4889/checks?check_run_id=1081965926

**Comment by kyleam** [comment]
I've got a matching singularity locally (2.6.1-2 from neurodebian), but haven't been able to trigger the failure.

**Comment by kyleam** [comment]
I triggered a Travis build for this repo.  The same error happens here too: https://travis-ci.org/github/datalad/datalad-container/builds/725361071

**Comment by adswa** [comment]
I tried to trigger it locally without success on a machine with Python 3.7.3 and singularity 2.6.1-dist and on one with Python 3.8.5 and singularity 3.5.2+ds1. Doesn't help at all, but I wanted to share as FYI.

**Comment by kyleam** [comment]
@adswa Thanks for checking!

**Comment by kyleam** [comment]
@yarikoptic worked his magic and fixed this behind the scenes in neurodebian.  Thank you!

https://github.com/datalad/datalad/pull/4927#issuecomment-694428504

**Comment by kyleam** [comment]
Hmm, didn't look closely, but the test is still failing in this repo's Travis build.  Here's  a build with a scratch branch on the same commit as master: https://travis-ci.org/github/datalad/datalad-container/builds/728134668

**Comment by yarikoptic** [comment]
ok, I did port that patch to C: https://salsa.debian.org/hpc-team/singularity-container/-/blob/neurodebian/debian/patches/bf-backport-loopmode and uploaded to +nd2 to neurodebian. Restarted the build https://travis-ci.org/github/datalad/datalad-container/builds/730116126 - and runs are coming out (some are yet to complete) green!

**Comment by kyleam** [comment]
Thank you!
