### ISSUE TITLE
Windows: os.getid() and os.getgid are not available

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-container#138]
(I'm already sorry for each Windows issue I post)

Running a container on Windows fails early on, because the ``os`` module does not include ``getuid`` and ``getgid`` on windows:

```
$ datalad containers-run
[INFO] Making sure inputs are available (this may take some time)
[INFO] == Command start (output follows) =====
[ERROR] Failed to execute ['c:\\users\\datalad\\repos\\datalad-container\\datalad_container\\adapters\\docker.py', 'run', '.datalad\\environments\\software\\image']
Traceback (most recent call last):
  File "c:\users\datalad\repos\datalad-container\datalad_container\adapters\docker.py", line 199, in <module>
    main(sys.argv)
  File "c:\users\datalad\repos\datalad-container\datalad_container\adapters\docker.py", line 194, in main
    namespace.func(namespace)
  File "c:\users\datalad\repos\datalad-container\datalad_container\adapters\docker.py", line 140, in cli_run
    "-u", "{}:{}".format(os.getuid(), os.getgid()),
AttributeError: module 'os' has no attribute 'getuid'
Failed to execute ['c:\\users\\datalad\\repos\\datalad-container\\datalad_container\\adapters\\docker.py', 'run', '.datalad\\environments\\software\\image']
Traceback (most recent call last):
  File "c:\users\datalad\repos\datalad-container\datalad_container\adapters\docker.py", line 199, in <module>
    main(sys.argv)
  File "c:\users\datalad\repos\datalad-container\datalad_container\adapters\docker.py", line 194, in main
    namespace.func(namespace)
  File "c:\users\datalad\repos\datalad-container\datalad_container\adapters\docker.py", line 140, in cli_run
    "-u", "{}:{}".format(os.getuid(), os.getgid()),
AttributeError: module 'os' has no attribute 'getuid'
[INFO] == Command exit (modification check follows) =====
[INFO] The command had a non-zero exit code. If this is expected, you can save the changes with 'datalad save -d . -r -F .git\COMMIT_EDITMSG'
CommandError: 'python.exe -m datalad_container.adapters.docker run .datalad\environments\software\image ' failed with exitcode 1 under C:/Users/datalad/testing/containerdataset
```

**Comment by kyleam** [comment]
I think not adding `-u` on Windows is a good first step.  Any permission issues that come along with dropping `-u` are of course better than not working at all.  Could you open a PR?

---

When I looked at this again for the skopeo PR, I left a note in the new adapter [1] that setting `-u` here is questionable.  It fixes the permissions issue, but some commands won't be happy if those IDs don't exist in the container.

https://github.com/datalad/datalad-container/blob/290743a9c84d3123bfff8b8ef05e88faf4b853d4/datalad_container/adapters/oci.py#L354-L356

[1] yes, ideally this logic wouldn't be repeated in the two adapters

**Comment by adswa** [comment]
>  Could you open a PR?

Gave it a try in #140  :)

**Comment by kyleam** [comment]
Thanks, Adina.  The workaround is merged.  Let's see how that plays out and open a dedicated issue if permission problems pop up on Windows.
