### ISSUE TITLE
2 tests fail locally: test_add_noop and test_docker

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-container#85]
```shell
$ python -m nose -s -v datalad_container
...
======================================================================
ERROR: datalad_container.tests.test_containers.test_add_noop
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-container/datalad_container/tests/test_containers.py", line 42, in test_add_noop
    on_failure='ignore')
  File "/home/yoh/proj/datalad/datalad-master/datalad/distribution/dataset.py", line 527, in apply_func
    return f(**kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 490, in eval_func
    return return_func(generator_func)(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 478, in return_func
    results = list(results)
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 427, in generator_func
    result_renderer, result_xfm, _result_filter, **_kwargs):
  File "/home/yoh/proj/datalad/datalad-master/datalad/interface/utils.py", line 520, in _process_results
    for res in results:
  File "/home/yoh/proj/datalad/datalad-container/datalad_container/containers_add.py", line 249, in __call__
    copyfile(url, image)
  File "/usr/lib/python2.7/shutil.py", line 97, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/home/yoh/.tmp/datalad_temp_test_add_noopcjESpu/dummy'

======================================================================
FAIL: datalad_container.tests.test_schemes.test_docker
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 841, in newfunc
    return func(*args, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 607, in newfunc
    return t(*(arg + (filename,)), **kw)
  File "/home/yoh/proj/datalad/datalad-container/datalad_container/tests/test_schemes.py", line 33, in test_docker
    re_=True, match=False)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 415, in ok_file_has_content
    assert_re_in(content, file_content, **kwargs)
  File "/home/yoh/proj/datalad/datalad-master/datalad/tests/utils.py", line 1158, in assert_re_in
    msg or "Not a single entry matched %r in %r" % (regex, c)
AssertionError: Not a single entry matched 'There is no runscript defined for this container' in ['#!/bin/sh\nOCI_ENTRYPOINT=\'\'\nOCI_CMD=\'"sh"\'\n# ENTRYPOINT only - run entrypoint plus args\nif [ -z "$OCI_CMD" ] && [ -n "$OCI_ENTRYPOINT" ]; then\n    SINGULARITY_OCI_RUN="${OCI_ENTRYPOINT} $@"\nfi\n\n# CMD only - run CMD or override with args\nif [ -n "$OCI_CMD" ] && [ -z "$OCI_ENTRYPOINT" ]; then\n    if [ $# -gt 0 ]; then\n        SINGULARITY_OCI_RUN="$@"\n    else\n        SINGULARITY_OCI_RUN="${OCI_CMD}"\n    fi\nfi\n\n# ENTRYPOINT and CMD - run ENTRYPOINT with CMD as default args\n# override with user provided args\nif [ $# -gt 0 ]; then\n    SINGULARITY_OCI_RUN="${OCI_ENTRYPOINT} $@"\nelse\n    SINGULARITY_OCI_RUN="${OCI_ENTRYPOINT} ${OCI_CMD}"\nfi\n\neval ${SINGULARITY_OCI_RUN}\n\n']
```

is that happening just to me?

**Comment by kyleam** [comment]
test_add_noop works for me locally.

test_docker fails for me with Singularity **3**.  I'll update that check to be less brittle.

**Comment by yarikoptic** [comment]
test_add_noop -- ha ha ha 

```shell
(git)hopa:~datalad/datalad-container[master]git
$> ls -ld bogus
-rw------- 1 yoh yoh 0 Apr 19 16:14 bogus
```

so, a month ago somehow bogus was born.  code/test relies on testing if url (with value `"bogus"` in the test) points to a file which exists, test runs within code base, picks up this poor bogus, tries to copy over previously annexed file.  So I think there are 2 issues unraveled:

1. test should not rely on (absence of) files in the local file tree
2. probably we should first `rm` the destination image file before calling `copyfile` if it already `lexists`.

Since I am at it, will send a quick PR

**Comment by yarikoptic** [comment]
although not sure if `2.` shouldn't be treated as feature, although relying on `git-annex` protection.  If to be a feature -- should be more explicit with a good error message imho.  Thus still sending a PR

**Comment by kyleam** [comment]
Should both now be addressed.
